package ir.reza_mahmoudi.newsgram.core.util.list

val sortByItems: Map<String?, String> = mapOf(
    "publishedAt" to "Published At",
    "relevancy" to "Relevancy",
    "popularity" to "Popularity"
)
val categoryItems: Map<String?, String> = mapOf(
    "general" to "General",
    "sports" to "Sports",
    "business" to "Business",
    "entertainment" to "Entertainment",
    "health" to "Health",
    "science" to "Science",
    "technology" to "Technology",
)

val languageItems: Map<String?, String> = mapOf(
    null to "All",
    "en" to "English",
    "de" to "German",
    "es" to "Spanish",
    "fr" to "French",
    "it" to "Italian",
    "no" to "Norwegian",
    "pt" to "Portuguese",
    "ru" to "Russian",
    "sv" to "Swedish",
    "ar" to "Arabic",
    "zh" to "Chinese"
)

val countryItems: Map<String?, String> = mapOf(
    null to "All",
    "us" to "United States",
    "gb" to "United Kingdom",
    "de" to "Germany",
    "it" to "Italy",
    "fr" to "France",
    "ar" to "Argentina",
    "at" to "Austria",
    "au" to "Australia",
    "be" to "Belgium",
    "bg" to "Bulgaria",
    "br" to "Brazil",
    "ca" to "Canada",
    "ch" to "Switzerland",
    "cn" to "China",
    "co" to "Colombia",
    "cu" to "Cuba",
    "cz" to "Czech Republic",
    "eg" to "Egypt",
    "gr" to "Greece",
    "hk" to "Hong Kong",
    "hu" to "Hungary",
    "id" to "Indonesia",
    "ie" to "Ireland",
    "in" to "India",
    "jp" to "Japan",
    "kr" to "South Korea",
    "lt" to "Lithuania",
    "lv" to "Latvia",
    "ma" to "Morocco",
    "mx" to "Mexico",
    "my" to "Malaysia",
    "ng" to "Nigeria",
    "nl" to "Netherlands",
    "no" to "Norway",
    "nz" to "New Zealand",
    "ph" to "Philippines",
    "pl" to "Poland",
    "pt" to "Portugal",
    "ro" to "Romania",
    "rs" to "Serbia",
    "ru" to "Russia",
    "se" to "Sweden",
    "sg" to "Singapore",
    "si" to "Slovenia",
    "sk" to "Slovakia",
    "th" to "Thailand",
    "tr" to "Turkey",
    "tw" to "Taiwan",
    "ua" to "Ukraine",
    "ve" to "Venezuela",
    "za" to "South Africa",
    "ae" to "United Arab Emirates",
)